// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEC-5m7o-AV9vQWQtKsokhbO_ErxIT42I',
    appId: '1:510814618249:web:2727504c9a21aa7c787c58',
    messagingSenderId: '510814618249',
    projectId: 'd-write-2f2a3',
    authDomain: 'd-write-2f2a3.firebaseapp.com',
    storageBucket: 'd-write-2f2a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7TNk9FdtUW00khd3k7X13lczzCeqmmPg',
    appId: '1:510814618249:android:a58c2293a9dbf63a787c58',
    messagingSenderId: '510814618249',
    projectId: 'd-write-2f2a3',
    storageBucket: 'd-write-2f2a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC_oO70ifqBk7fHf5EwtlT9S_YwvglvdE',
    appId: '1:510814618249:ios:bc3da97a72686c8d787c58',
    messagingSenderId: '510814618249',
    projectId: 'd-write-2f2a3',
    storageBucket: 'd-write-2f2a3.firebasestorage.app',
    iosBundleId: 'com.example.dWrite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiIpNzGA7XIbLUFtwr40f2-3ZRc3hGifw',
    appId: '1:279320808556:ios:eb0f752c66db8f38e0dc49',
    messagingSenderId: '279320808556',
    projectId: 'd-write-d7aac',
    storageBucket: 'd-write-d7aac.firebasestorage.app',
    iosBundleId: 'com.example.dWrite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEC-5m7o-AV9vQWQtKsokhbO_ErxIT42I',
    appId: '1:510814618249:web:3650d3e253053a89787c58',
    messagingSenderId: '510814618249',
    projectId: 'd-write-2f2a3',
    authDomain: 'd-write-2f2a3.firebaseapp.com',
    storageBucket: 'd-write-2f2a3.firebasestorage.app',
  );

}