// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJuwW6YInNEm72jVMOHEj-yZ6giOFy9hk',
    appId: '1:279320808556:web:afd76eb8b1f2add5e0dc49',
    messagingSenderId: '279320808556',
    projectId: 'd-write-d7aac',
    authDomain: 'd-write-d7aac.firebaseapp.com',
    storageBucket: 'd-write-d7aac.firebasestorage.app',
    measurementId: 'G-8D1C03DNPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeYDH6KID2ohAt6W9T5NxHvKeykBNqXqY',
    appId: '1:279320808556:android:abec051c8eadb308e0dc49',
    messagingSenderId: '279320808556',
    projectId: 'd-write-d7aac',
    storageBucket: 'd-write-d7aac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiIpNzGA7XIbLUFtwr40f2-3ZRc3hGifw',
    appId: '1:279320808556:ios:eb0f752c66db8f38e0dc49',
    messagingSenderId: '279320808556',
    projectId: 'd-write-d7aac',
    storageBucket: 'd-write-d7aac.firebasestorage.app',
    iosBundleId: 'com.example.dWrite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiIpNzGA7XIbLUFtwr40f2-3ZRc3hGifw',
    appId: '1:279320808556:ios:eb0f752c66db8f38e0dc49',
    messagingSenderId: '279320808556',
    projectId: 'd-write-d7aac',
    storageBucket: 'd-write-d7aac.firebasestorage.app',
    iosBundleId: 'com.example.dWrite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJuwW6YInNEm72jVMOHEj-yZ6giOFy9hk',
    appId: '1:279320808556:web:17856b4ed5c6821fe0dc49',
    messagingSenderId: '279320808556',
    projectId: 'd-write-d7aac',
    authDomain: 'd-write-d7aac.firebaseapp.com',
    storageBucket: 'd-write-d7aac.firebasestorage.app',
    measurementId: 'G-8CZPH66FBT',
  );
}
